### ISSUE TITLE
Color scheme problems

### ISSUE THREAD

**Issue by ulgens** [anze3db/django-tui#6]
I'm having issues with the color scheme under macOS / iterm / zsh. In short, this is the issue:

![CleanShot 2024-08-06 at 16 01 26@2x](https://github.com/user-attachments/assets/bc0d284b-3df4-4aa4-8ca2-d8f5fd295958)

In comparison to [what shown in README](https://github.com/anze3db/django-tui/assets/513444/54bc6c84-267c-4e28-9d49-8b30391470ea), colors look boring / flat / harder to read.

I'm not doing anything interesting with iterm's color schemes and I never had any issue with lost / altered colors before. Is there anything we should be careful about to get better colors, closer to what shown in the docs?

**Comment by anze3db** [comment]
Hey @ulgens, I agree that really doesn't look great 😞 

It looks like the background colors are not being rendered, but I don't really understand why. I went through my own iterm settings, but can't seem to reproduce what you are seeing.

Can you let me know the versions of `textual` and `trogon` that you are using? You should be able to see them with:

```
❯ pip freeze | grep -E 'textual|trogon'
```

It's working fine for me on:

```
textual==0.74.0
trogon==0.5.0
```

but I'll also try on the exact versions that you are on to make sure it's not a problem with upstream dependencies.

Also, have you tried running any other textual apps? There is a [list of them here](https://github.com/oleksis/awesome-textualize-projects?tab=readme-ov-file#third-party-applications). If you have the same issue with any of these then it might be a problem with textual itself and we'll have to make a ticket there before I can fix it in django-tui.

**Comment by ulgens** [comment]
I think I looked for the issue in the wrong place. Apparently, things work just fine locally.

![CleanShot 2024-08-07 at 11 08 01@2x](https://github.com/user-attachments/assets/ac9b453b-099e-466c-822c-dc31f72a5463)

The issue occurs when I run it in a Docker container. At the moment, with the same textual and trogon versions, it works just fine without Docker.

The code/project I'm doing this test is https://github.com/ulgens/django-blasphemy/pull/559 , I hope the problem is easily replicable. I'll check how other apps act when I have the time.

Thanks for the help and the quick response.

**Comment by ulgens** [comment]
Hey again, once I knew Docker was to blame, it took seconds to find the solution 😬 The env var recommended at https://stackoverflow.com/a/33499558/1726238 solved the issue, and now I have a much fancier-looking result.

**Comment by anze3db** [comment]
Awesome that you managed to solve this, I didn't know docker limits the colors, thanks for letting me know!
